# Generated by Django 5.0.4 on 2024-04-08 09:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_card', models.CharField(max_length=12, unique=True, verbose_name='Aadhaar Card Number')),
                ('name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('password', models.CharField(default='password@123', max_length=255, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Purchased')),
                ('discount_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Discount Percentage')),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], default='Cash', max_length=5, verbose_name='Payment Method')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time of Purchase')),
                ('total_amount', models.FloatField(verbose_name='Total Amount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='Customer Name')),
                ('sales_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employee', verbose_name='Sales Person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Product Name')),
            ],
        ),
    ]
